FROM zambon/ubuntu-multi:16.04

ARG DOCKER_VERSION=1.10.3
ARG DAPPER_HOST_ARCH
ENV HOST_ARCH=${DAPPER_HOST_ARCH} ARCH=${DAPPER_HOST_ARCH}

RUN apt-get -q update && \
    apt-get -qy install \
      uuid-runtime \
      iptables \
      libapparmor-dev \
      curl \
      git \
      gcc \
    && rm -rf /var/lib/apt/lists/* && \
    rm -f /bin/sh && ln -s /bin/bash /bin/sh

ENV GOLANG_ARCH_amd64=amd64 GOLANG_ARCH_arm=armv6l GOLANG_ARCH_ppc64le=ppc64le \
    GOLANG_ARCH=GOLANG_ARCH_${ARCH} GOPATH=/go \
    PATH=/go/bin:/usr/local/go/bin:${PATH} SHELL=/bin/bash

RUN curl -fsSL https://storage.googleapis.com/golang/go1.7.4.linux-${!GOLANG_ARCH}.tar.gz | \
      tar -xzf - -C /usr/local && \
    go get github.com/rancher/trash && go get github.com/golang/lint/golint

RUN go get github.com/rancher/trash && \
    go get github.com/golang/lint/golint

RUN curl -sfL https://cocl.us/docker-${DOCKER_VERSION}-${ARCH}.tgz | \
      tar -xzf - -C /usr/bin --strip-components=1

ENV PATH /go/bin:$PATH
ENV DAPPER_SOURCE /go/src/github.com/rancher/agent
ENV DAPPER_OUTPUT bin dist
ENV DAPPER_ENV TAG REPO
ENV DAPPER_RUN_ARGS --privileged
ENV GO15VENDOREXPERIMENT 1
ENV TRASH_CACHE ${DAPPER_SOURCE}/.trash-cache
WORKDIR ${DAPPER_SOURCE}

RUN apt-get -q update && \
    apt-get -qy install python-tox && \
    rm -rf /var/lib/apt/lists/*

VOLUME "/var/lib/docker"

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
